import * as fs from "node:fs";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import {
  applyCursorRules,
  generateClaudeRules,
  mergeRulesIndexForVendor,
  readRules,
} from "./rules.js";

vi.mock("node:fs", () => ({
  existsSync: vi.fn(),
  mkdirSync: vi.fn(),
  readFileSync: vi.fn(),
  readdirSync: vi.fn(),
  writeFileSync: vi.fn(),
  cpSync: vi.fn(),
  chmodSync: vi.fn(),
  lstatSync: vi.fn(),
  readlinkSync: vi.fn(),
  realpathSync: vi.fn(),
  renameSync: vi.fn(),
  copyFileSync: vi.fn(),
  unlinkSync: vi.fn(),
}));

const mockTargetDir = "/tmp/test-project";

/**
 * Recover the content that landed at a path ending in `suffix`.
 *
 * Rule files are written atomically, so the payload goes to a temp sibling and
 * only reaches its real name via renameSync — the destination has to be read
 * back off the rename rather than off the write.
 */
function findAtomicWrite(
  suffix: string,
): { path: string; content: string } | undefined {
  const renames = (fs.renameSync as unknown as ReturnType<typeof vi.fn>).mock
    .calls as [string, string][];
  const writes = (fs.writeFileSync as unknown as ReturnType<typeof vi.fn>).mock
    .calls as [string, string][];

  for (const [tmp, dest] of renames) {
    if (typeof dest !== "string" || !dest.endsWith(suffix)) continue;
    const write = writes.find(([target]) => target === tmp);
    if (write) return { path: dest, content: write[1] };
  }
  return undefined;
}

describe("readRules", () => {
  beforeEach(() => vi.clearAllMocks());
  afterEach(() => vi.restoreAllMocks());

  it("should return empty array when rules dir does not exist", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      false,
    );
    expect(readRules(mockTargetDir)).toEqual([]);
  });

  it("should parse frontmatter fields from rule files", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (file: string) => !String(file).includes("oma-config"),
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      '---\ndescription: Frontend standards\nglobs: "**/*.tsx"\nalwaysApply: false\n---\n\n# Frontend',
    );

    const rules = readRules(mockTargetDir);
    expect(rules).toHaveLength(1);
    expect(rules[0]?.name).toBe("frontend");
    expect(rules[0]?.description).toBe("Frontend standards");
    expect(rules[0]?.globs).toBe("**/*.tsx");
    expect(rules[0]?.alwaysApply).toBe(false);
    expect(rules[0]?.body).toContain("# Frontend");
  });

  it("should filter non-.md files", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (file: string) => !String(file).includes("oma-config"),
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      ".gitkeep",
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: test\n---\n\n# Test",
    );

    expect(readRules(mockTargetDir)).toHaveLength(1);
  });
});

describe("applyCursorRules", () => {
  beforeEach(() => vi.clearAllMocks());
  afterEach(() => vi.restoreAllMocks());

  it("should return empty array when no rules exist", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      false,
    );
    expect(applyCursorRules(mockTargetDir)).toEqual([]);
  });

  it("should generate .mdc files with Cursor frontmatter", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (file: string) => !String(file).includes("oma-config"),
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      '---\ndescription: Frontend standards\nglobs: "**/*.{tsx,jsx}"\nalwaysApply: false\n---\n\n# Frontend\n\n1. Use React',
    );

    const result = applyCursorRules(mockTargetDir);
    expect(result).toEqual(["frontend"]);

    const writeCall = findAtomicWrite(".mdc");

    expect(writeCall).toBeDefined();
    const content = writeCall?.content as string;
    expect(content).toContain('description: "Frontend standards"');
    expect(content).toContain('globs: "**/*.{tsx,jsx}"');
    expect(content).toContain("alwaysApply: false");
    expect(content).toContain("# Frontend");
    expect(content).toContain("<!-- Generated by oh-my-agent");
  });

  it("should respect alwaysApply: true", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (file: string) => !String(file).includes("oma-config"),
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "i18n.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: i18n\nalwaysApply: true\n---\n\n# i18n",
    );

    applyCursorRules(mockTargetDir);

    const writeCall = findAtomicWrite(".mdc");

    expect(writeCall?.content as string).toContain("alwaysApply: true");
  });
});

describe("generateClaudeRules", () => {
  beforeEach(() => vi.clearAllMocks());
  afterEach(() => vi.restoreAllMocks());

  it("should return empty array when no rules exist", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      false,
    );
    expect(generateClaudeRules(mockTargetDir)).toEqual([]);
  });

  it("should generate .md files with paths frontmatter for scoped rules", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (file: string) => !String(file).includes("oma-config"),
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      '---\ndescription: Frontend standards\nglobs: "**/*.{tsx,jsx}"\nalwaysApply: false\n---\n\n# Frontend',
    );

    const result = generateClaudeRules(mockTargetDir);
    expect(result).toEqual(["frontend"]);

    const writeCall = findAtomicWrite("frontend.md");

    expect(writeCall).toBeDefined();
    const content = writeCall?.content as string;
    expect(content).toContain("description:");
    expect(content).toContain("paths: ");
    expect(content).toContain("**/*.{tsx,jsx}");
    expect(content).toContain("# Frontend");
  });

  it("should omit paths for alwaysApply rules", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (file: string) => !String(file).includes("oma-config"),
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "i18n.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: i18n\nalwaysApply: true\n---\n\n# i18n",
    );

    generateClaudeRules(mockTargetDir);

    const writeCall = findAtomicWrite("i18n.md");

    const content = writeCall?.content as string;
    expect(content).not.toContain("paths:");
  });
});

describe("mergeRulesIndexForVendor", () => {
  beforeEach(() => vi.clearAllMocks());
  afterEach(() => vi.restoreAllMocks());

  it("should return false for unsupported vendor", () => {
    expect(mergeRulesIndexForVendor(mockTargetDir, "unknown-vendor")).toBe(
      false,
    );
  });

  it("should still generate usage guide even without rules", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        if (typeof p === "string" && p.endsWith("CLAUDE.md")) return false;
        if (typeof p === "string" && p.includes(".agents/rules")) return false;
        return false;
      },
    );

    const result = mergeRulesIndexForVendor(mockTargetDir, "claude");
    expect(result).toBe(true);

    const writeCall = findAtomicWrite("CLAUDE.md");
    expect(writeCall).toBeDefined();
    const content = writeCall?.content as string;
    expect(content).toContain("# oh-my-agent");
    expect(content).toContain("## Workflows");
    expect(content).not.toContain("## Project Rules");
  });

  it("no longer generates GEMINI.md for the deprecated gemini vendor", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      false,
    );

    const result = mergeRulesIndexForVendor(mockTargetDir, "gemini");

    // gemini is no longer a single-file vendor → no-op, nothing written.
    expect(result).toBe(false);
    expect(findAtomicWrite("GEMINI.md")).toBeUndefined();
  });

  it("should create CLAUDE.md with usage guide and rules index", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        const norm = typeof p === "string" ? p.replace(/\\/g, "/") : "";
        if (norm.endsWith("CLAUDE.md")) return false;
        return norm.includes(".agents/rules");
      },
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
      "backend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      '---\ndescription: test\nglobs: "**/*.tsx"\n---\n\n# Test',
    );

    const result = mergeRulesIndexForVendor(mockTargetDir, "claude");
    expect(result).toBe(true);

    const writeCall = findAtomicWrite("CLAUDE.md");
    expect(writeCall).toBeDefined();
    const content = writeCall?.content as string;
    expect(content).toContain("<!-- OMA:START");
    expect(content).toContain("<!-- OMA:END -->");
    expect(content).toContain("# oh-my-agent");
    expect(content).toContain("## Code Search");
    expect(content).toContain(
      "Serena MCP is required for code search and discovery.",
    );
    expect(content).toContain("only when Serena is unavailable or times out");
    expect(content).toContain("execution-policy.md");
    expect(content).toContain("unless the user explicitly requests a build");
    expect(content).toContain("Do not modify `.agents/` definitions");
    expect(content).toContain("`.agents/results/` and `.agents/state/`");
    expect(content).not.toContain("max_answer_chars");
    expect(content).not.toContain("| Task | Preferred tool |");
    expect(content).not.toContain("## Auto-Detection");
    expect(content).toContain("## Workflows");
    expect(content).toContain("| frontend |");
    expect(content).toContain("| backend |");
    expect(content).toContain(".agents/rules/");
    expect(content).toContain(
      "Write non-ASCII tool-call parameters as literal UTF-8, not Unicode escapes.",
    );
  });

  it("should create AGENTS.md for codex vendor", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        if (typeof p === "string" && p.endsWith("AGENTS.md")) return false;
        return p.includes(".agents/rules");
      },
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: test\n---\n\n# Test",
    );

    mergeRulesIndexForVendor(mockTargetDir, "codex");

    const writeCall = findAtomicWrite("AGENTS.md");
    expect(writeCall).toBeDefined();
  });

  it("should write CLAUDE.md for claude vendor", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        if (typeof p === "string" && p.endsWith("CLAUDE.md")) return false;
        return p.includes(".agents/rules");
      },
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: test\n---\n\n# Test",
    );

    mergeRulesIndexForVendor(mockTargetDir, "claude");

    const writeCall = findAtomicWrite("CLAUDE.md");
    expect(writeCall).toBeDefined();
  });

  it("should write AGENTS.md for qwen vendor (shared with codex)", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        if (typeof p === "string" && p.endsWith("AGENTS.md")) return false;
        return p.includes(".agents/rules");
      },
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: test\n---\n\n# Test",
    );

    mergeRulesIndexForVendor(mockTargetDir, "qwen");

    const writeCall = findAtomicWrite("AGENTS.md");
    expect(writeCall).toBeDefined();
  });

  it("should write AGENTS.md for cursor vendor", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        if (typeof p === "string" && p.endsWith("AGENTS.md")) return false;
        return p.includes(".agents/rules");
      },
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: test\n---\n\n# Test",
    );

    mergeRulesIndexForVendor(mockTargetDir, "cursor");

    const writeCall = findAtomicWrite("AGENTS.md");
    expect(writeCall).toBeDefined();
  });

  it("describes every vendor sharing AGENTS.md, in a trigger-independent order", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        if (typeof p === "string" && p.endsWith("AGENTS.md")) return false;
        return p.includes(".agents/rules");
      },
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: test\n---\n\n# Test",
    );

    // `oma link cursor` on a project that also has codex configured.
    mergeRulesIndexForVendor(mockTargetDir, "cursor", ["codex", "claude"]);
    const viaCursor = findAtomicWrite("AGENTS.md")?.content as string;

    expect(viaCursor).toContain("- codex: ");
    expect(viaCursor).toContain(".codex/agents/{name}.toml");
    expect(viaCursor).toContain("- cursor: ");
    expect(viaCursor).toContain("`@agent-name`");
    expect(viaCursor).not.toContain("Hooks (codex):");
    expect(viaCursor).not.toContain("Hooks (cursor):");
    // claude writes CLAUDE.md — it must not leak into the shared AGENTS.md.
    expect(viaCursor).not.toContain("- claude: ");
    expect(viaCursor).not.toContain("Write non-ASCII");

    // The unfiltered run starts from codex instead; same file, same bytes.
    vi.clearAllMocks();
    mergeRulesIndexForVendor(mockTargetDir, "codex", ["cursor", "claude"]);
    const viaCodex = findAtomicWrite("AGENTS.md")?.content as string;
    expect(viaCodex).toBe(viaCursor);
  });

  it("keeps the single-vendor block flat when no vendor shares the doc", () => {
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        if (typeof p === "string" && p.endsWith("AGENTS.md")) return false;
        return p.includes(".agents/rules");
      },
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue(
      "---\ndescription: test\n---\n\n# Test",
    );

    mergeRulesIndexForVendor(mockTargetDir, "cursor", ["claude", "kimi"]);

    const content = findAtomicWrite("AGENTS.md")?.content as string;
    expect(content).toContain("- **Subagents**: `@agent-name`");
    expect(content).not.toContain("UserPromptSubmit");
    expect(content).not.toContain("Hooks (cursor):");
  });

  it("should replace existing OMA block on update", () => {
    const omaStart = "<!-- OMA:START";
    const omaEnd = "<!-- OMA:END -->";
    (fs.existsSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (file: string) => !String(file).includes("oma-config"),
    );
    (fs.readdirSync as unknown as ReturnType<typeof vi.fn>).mockReturnValue([
      "frontend.md",
    ]);
    (fs.readFileSync as unknown as ReturnType<typeof vi.fn>).mockImplementation(
      (p: string) => {
        if (typeof p === "string" && p.endsWith("AGENTS.md")) {
          return `# My Project\n\nCustom content\n\n${omaStart} -->\nold block\n${omaEnd}\n\nMore user content`;
        }
        return "---\ndescription: test\n---\n\n# Test";
      },
    );

    mergeRulesIndexForVendor(mockTargetDir, "codex");

    const writeCall = findAtomicWrite("AGENTS.md");
    const content = writeCall?.content as string;
    expect(content).toContain("# My Project");
    expect(content).toContain("Custom content");
    expect(content).toContain("More user content");
    expect(content).toContain(omaStart);
    expect(content).not.toContain("old block");
    expect(content).toContain("# oh-my-agent");
  });
});
